---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:hello-world-servlet-example.war
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://3.19.61.46:8080/service/local/artifact/maven/redirect?r=releases&g=com.geekcap.vmturbo&a=hello-world-servlet-example&p=war&v=LATEST
       dest: /usr/share/tomcat/webapps/hello-world-servlet-example.war
  - name: Start Tomcat
    service: name=tomcat state=started
